### ISSUE TITLE
Lexic issue after running jekyll serve

### ISSUE THREAD

**Issue by roadev** [railsgirls-cali/railsgirls-cali.github.io#3]
```bash
jekyll serve --watch 
Configuration file: /home/jroa/Documents/railsgirls-cali.github.io/_config.yml
            Source: .
       Destination: ./_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Conversion error: Jekyll::Converters::Markdown encountered an error while converting '/_pages/instagram.md':
                    Traceback (most recent call last): File "/home/jroa/.rvm/gems/ruby-2.3.0/gems/pygments.rb-0.6.3/lib/pygments/mentos.py", line 303, in start res = self.get_data(method, lexer, args, kwargs, text) File "/home/jroa/.rvm/gems/ruby-2.3.0/gems/pygments.rb-0.6.3/lib/pygments/mentos.py", line 171, in get_data res = self.highlight_text(text, lexer, formatter_name, args, _convert_keys(opts)) File "/home/jroa/.rvm/gems/ruby-2.3.0/gems/pygments.rb-0.6.3/lib/pygments/mentos.py", line 122, in highlight_text lexer = self.return_lexer(lexer, args, kwargs, code) File "/home/jroa/.rvm/gems/ruby-2.3.0/gems/pygments.rb-0.6.3/lib/pygments/mentos.py", line 79, in return_lexer return lexers.get_lexer_by_name(lexer, **inputs) File "/home/jroa/.rvm/gems/ruby-2.3.0/gems/pygments.rb-0.6.3/vendor/pygments-main/pygments/lexers/__init__.py", line 98, in get_lexer_by_name raise ClassNotFound('no lexer for alias %r found' % _alias) ClassNotFound: no lexer for alias 'shell' found 
jekyll 3.1.3 | Error:  Traceback (most recent call last):
  File "/home/jroa/.rvm/gems/ruby-2.3.0/gems/pygments.rb-0.6.3/lib/pygments/mentos.py", line 303, in start
    res = self.get_data(method, lexer, args, kwargs, text)
  File "/home/jroa/.rvm/gems/ruby-2.3.0/gems/pygments.rb-0.6.3/lib/pygments/mentos.py", line 171, in get_data
    res = self.highlight_text(text, lexer, formatter_name, args, _convert_keys(opts))
  File "/home/jroa/.rvm/gems/ruby-2.3.0/gems/pygments.rb-0.6.3/lib/pygments/mentos.py", line 122, in highlight_text
    lexer = self.return_lexer(lexer, args, kwargs, code)
  File "/home/jroa/.rvm/gems/ruby-2.3.0/gems/pygments.rb-0.6.3/lib/pygments/mentos.py", line 79, in return_lexer
    return lexers.get_lexer_by_name(lexer, **inputs)
  File "/home/jroa/.rvm/gems/ruby-2.3.0/gems/pygments.rb-0.6.3/vendor/pygments-main/pygments/lexers/__init__.py", line 98, in get_lexer_by_name
    raise ClassNotFound('no lexer for alias %r found' % _alias)
ClassNotFound: no lexer for alias 'shell' found
```

**Comment by roadev** [comment]
Fixed with #4
